### ISSUE TITLE
SortableAdminMixin safari & mac chrome not usable

### ISSUE THREAD

**Issue by wullerot** [rouxcode/django-admin-sort#26]

**Comment by wullerot** [comment]
frontend js
related #25

**Comment by benzkji** [comment]
[tbody needs id?, stackoverflow](http://stackoverflow.com/questions/25160616/sortable-js-none-jquery-plugin-sorts-divs-but-not-tables)
[mor info (tbody, rubaxa issues)](https://github.com/RubaXa/Sortable/issues/639)
[even more, rubaxa issues](https://github.com/RubaXa/Sortable/issues/1062)

**Comment by benzkji** [comment]
reminder? probably ok...

**Comment by benzkji** [comment]
lets open this again if it occurs again...works perfect in chrome(ium)
